#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 10 12:35:59 2023

@author: fernandoaguila
"""

import numpy as np
import matplotlib.pylab as plt
import os

# 10.05.2023 to add more data types when possible

def read_witec(direct):
    """
    Function to read the data from file generated by Witec software

    Parameters
    ----------
    direct : String
        String with the directory of the file to be read.

    Returns
    -------
    temp_dict : Dic
        Dictionary with the x and y values.

    """

    # changing the directory to the one where the data files are
    # os.chdir(direct)

    # opening the files
    with open(direct, 'r') as file:
        # reading the lines (file.readlines) and storing them in a list, 
        # then separating the column elements (i.split('\t')) and storing them as separated elements in a list
        data=np.array([i.split(' ') for i in file.readlines()])
        
    
    r,c=np.shape(data)
    
    # convert all elements in data from string to float before plotting
    x=list(map(float,data[::,0]))
    # compute the mean for the raman signal measurements 
    y=[np.mean(list(map(float,data[k,1::]))) for k in range(r)]
    
    
    # creating dictionary to safe the data
    temp_dict={'x' :np.array(x), 'y': np.array(y)}
    
    
    return temp_dict

# def read_horiba(direct):
    
    